# Localhost

#GET ALL 
GET http://localhost:8080/users
Content-Type: application/json

###

#GET BY ID 
GET http://localhost:8080/users/666dcd79b9a81f922812be08
Content-Type: application/json
###

# Create Contacts 
POST http://localhost:8080/users/create HTTP/1.1
Content-Type: application/json

{
"firstName": "Brian", 
"lastName": "Bird", 
"email": "bb@ford.com", 
"favoriteColor": "Green", 
"birthday": "4/05/1991"
}

###

# Put Contanct 
PUT http://localhost:8080/users/update/666de0542256ad8758b3751e HTTP/1.1
Content-Type: application/json

{
"firstName": "Brody",
"lastName": "Bebefinn",
"email": "bebe@bebefinn",
"favoriteColor": "Green",
"birthday": "01/01/2023"
}

### 

# DeleteContact 
DELETE http://localhost:8080/users/delete/667752a49c4d0095e0eff37a HTTP/1.1

# Production

### # GET ALL 
GET https://ces341-web-service.onrender.com/users

### # GET BY ID 
GET https://ces341-web-service.onrender.com/users/6669dc78f96ab4e6d3722283

###

# Create Contacts 
POST https://ces341-web-service.onrender.com/users/create HTTP/1.1 content-type: application/json

{
"firstName": "Koko", "lastName": "Mambou", "email": "kokm@kolob.com", "favoriteColor": "Green", "birthday": "8/08/2023"
}

###


# Put Contanct 
PUT https://ces341-web-service.onrender.com/users/update/6669db8df96ab4e6d3722280 HTTP/1.1 Content-Type: application/json

{
"favoriteColor": "Orange"
}

### # DeleteContact 
DELETE https://ces341-web-service.onrender.com/users/delete/666dcde6b9a81f922812be09 HTTP/1.1